### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [huggingface/evaluation-guidebook#18]
Hi @clefourrier and @NathanHB ,

nice repository! Great that you are sharing it open source! I was just wondering under which conditions one could reuse the materials provided here, e.g. for teaching courses and therefore resharing your materials. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blog post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by clefourrier** [comment]
I need to update my knowledge about licenses a bit, but in the meantime you can assume I'm going to go for something like a cc-by-sa-nc.
Will confirm in the week!

**Comment by clefourrier** [comment]
Yep, going for CC-By-NV-SA!
